#!/bin/sh

echo "++ 99-custom_xrm"

while [ ! -e  /var/www/d-tacq/rc-user-complete ]; do
        sleep 10
        echo "defer 99-custom_xrm until IOC_READY"
done
echo custom_xrm $(cat /var/www/d-tacq/rc-user-complete)

HOSTNAME=$(hostname)

PRESENT428=0

# Site specific initialisation

for site in 1 2 3 4 5 6; do
    NAME_FILE="/etc/acq400/$site/module_name"
    TYPE_FILE="/etc/acq400/$site/module_type"

    if [ -f "$NAME_FILE" ] && [ -f "$TYPE_FILE" ]; then
        MOD_NAME=$(cat "$NAME_FILE")
        MOD_TYPE=$(cat "$TYPE_FILE")

        echo "Checking Site $site: Found $MOD_NAME (Type: $MOD_TYPE)"

        # Perform actions depending on the module name (or type)
        case "$MOD_NAME" in
            "acq423elf")
                echo "  -> Executing specific setup for acq423elf..."
                ;;
                
            "acq428elf")
                echo "  -> Executing specific setup for acq428elf..."
                caput ${HOSTNAME}:${site}:ADC_CAL calibrated
                caput ${HOSTNAME}:${site}:GAIN:ALL 1
                PRESENT428=1
                ;;

            "ao420fmc") # acq427 AO-only boards
                echo "  -> Executing specific setup for ao420fmc..."
                set.site $site clk 1,1,1
                set.site $site trg 1,1,1
                set.site $site CLKDIV 40
                caput ${HOSTNAME}:${site}:AO:GAIN:CH:ALL x2
                caput ${HOSTNAME}:${site}:AO:REF 5.0V
                ;;
                
            "dio482elf_xrm")
                echo "  -> Executing setup for dio482elf_xrm..."
                set.site $site clk 1,2,1
                set.site $site trg 1,2,1
                # if it has a 428 CLKDIV is 2 not 1
                if [ "$PRESENT428" -eq 1 ]; then
                    set.site $site CLKDIV 2
                else
                    set.site $site CLKDIV 1
                fi
                ;;
                
            *)
                echo "  -> Unrecognized module: $MOD_NAME"
                ;;
        esac 
    else
        echo "Checking Site $site: No module installed."
    fi
done

# Box specific initialization
echo "XRM specific flavor initialization"
XRM_MODEL=$(grep ^export /mnt/local/sysconfig/xrm_epics.sh | grep MODEL | sed 's/.*="//;s/"//')
echo "Detected XRM flavor : $XRM_MODEL"

APPLIANCE_TYPE=$XRM_MODEL
if [ "$APPLIANCE_TYPE" == "XRM-MagPS" ]; then
	run0_sites="1,5,6"
	spad_setting=1,14,0
	XRM_JUDGEMENT="4096 d0"
elif [ "$APPLIANCE_TYPE" == "XRM-QPMS" ]; then
	run0_sites="1,2,3,4"
	spad_setting=1,16,0
	XRM_JUDGEMENT="4096 d0"
elif [ "$APPLIANCE_TYPE" == "XRM-INST-A" ]; then
	run0_sites="1,2"
	spad_setting=1,16,0
	XRM_JUDGEMENT="16384 d0"
elif [ "$APPLIANCE_TYPE" == "XRM-INST-B" ]; then
	run0_sites="1,2,5"
	spad_setting=1,15,0
	XRM_JUDGEMENT="16384 d0"
else
	echo "No XRM detected"
	spad=0,0,0
fi

## SPADCOP WR_TAI_CURR_L - Include seconds since epcoch in SPAD
#                   enable,site,register,sample_us
# 0x208 is WR_TAI_CURR_L
set.site 0 spadcop3 1,2,0x208,1000

## uSec counter - Trigger the uSec counter at the same instant as Site 1
#s1_clk_setting=$(get.site 1 clk|cut -c 5-9)
s1_trg_setting=$(get.site 1 trg|cut -c 5-9)
set.site 0 spad1_us $s1_trg_setting

## SPAD_ID - Identity patterns in unused SPAD words
/usr/local/CARE/make_spad_id

## run0 configuration, including SPAD configuration
run0 $run0_sites $spad_setting

## Judgement setup
judgement() {
# short trace length, rapid update 50Hz possible
set.site 1 RTM_TRANSLEN ${1:-128}
set.site 1 RGM RTM
set.site 1 RGM:DX ${2:-d0}
set.site 1 RGM:SENSE rising
}
# see /mnt/local/sysconfig/epics.sh
# Maintiain the ability to override default in acq400.sh
source /mnt/local/sysconfig/acq400.sh

if [ ! -z "$ACQ400_JUDGEMENT" ]; then
	judgement $ACQ400_JUDGEMENT
else
	judgement $XRM_JUDGEMENT
fi
